name: Build/Test
on:
  push:
    branches:
      - main
    paths:
      - 'TcOscatBasic/**'
      - 'TcOscatBasic_TC3.1.4024/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  Build:
    name: Build/Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: Zeugwerk/zkbuild-action@1.0.0
        with:
          username: ${{ secrets.ACTIONS_ZGWK_USERNAME }}
          password: ${{ secrets.ACTIONS_ZGWK_PASSWORD }}
          tcversion: TC3.1.4026
      - name: Publish Unittest
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: archive/tests/**/TcUnit_xUnit_results.xml
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: TcOscatBasic
          path: |
            **/*library

  BuildTC4024:
    name: Build_TC3.1.4024
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: Zeugwerk/zkbuild-action@1.0.0
        with:
          username: ${{ secrets.ACTIONS_ZGWK_USERNAME }}
          password: ${{ secrets.ACTIONS_ZGWK_PASSWORD }}
          tcversion: TC3.1.4024.56
          workspace: TcOscatBasic_TC3.1.4024